# Default values for test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: $DOCKER_IMAGE
  tag: $DOCKER_TAG
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

podAnnotations: 
  app: front

service:
  type: ClusterIP
  port: "3000"

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, User"
  hosts:
    - host: $INGRESS_HOSTNAME
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


env: []
#   - name: maxPoolSize
#     value: $maxPoolSize
#   - name: db_password
#     value: $db_password
#   - name: url
#     value: $url
#   - name: db_username
#     value: $db_username
resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
